import { Request, Response } from 'express';
import * as Sentry from "@sentry/node";
import prisma from '../configs/prisma.js';
import { v2 as cloudinary } from 'cloudinary';
import { GenerateContentConfig, HarmBlockThreshold, HarmCategory } from '@google/genai';
import fs from 'fs';
import ai from '../configs/ai.js';
import axios from 'axios';
import path from 'path';

const loadImage=(filePath:string,mimeType:string)=>{
    return {
        inlineData:{
            data: fs.readFileSync(filePath, { encoding: 'base64' }),
            mimeType: mimeType,
        }
    }
}

export const createProject = async (req: Request, res: Response) => {
    try {
        const { userId } = req.auth();
        if (!userId) {
            return res.status(401).json({ message: "Unauthorized" });
        }

        const {
            name = 'New Project',
            aspectRatio,
            userPrompt,
            productName,
            productDescription,
            targetLength = 5,
        } = req.body;

        const images: any[] = (req.files as any[]) || [];

        if (!productName || images.length > 2) {
            return res
                .status(400)
                .json({ message: "Product name required and max 2 images allowed" });
        }

        const user = await prisma.user.findUnique({ where: { id: userId } });
        if (!user || user.credits < 5) {
            return res.status(401).json({ message: "Not enough credits" });
        }

        await prisma.user.update({
            where: { id: userId },
            data: { credits: { decrement: 5 } },
        });

        const uploadedImages = await Promise.all(
            images.map(async (image: any) => {
                const result = await cloudinary.uploader.upload(image.path, {
                    resource_type: "image",
                });
                return result.secure_url;
            })
        );

        const project = await prisma.project.create({
            data: {
                name,
                userId,
                productName,
                productDescription,
                targetLength: parseInt(targetLength.toString()),
                aspectRatio,
                userPrompt,
                uploadedImages,
                isGenerating: true,
            },
        });

        const model = "gemini-2.5-flash-image";

        const generationConfig: GenerateContentConfig = {
            maxOutputTokens: 32768,
            temperature: 1,
            topP: 0.95,
            // FIX: responseModalities must be lowercase
            responseModalities: ["text", "image"],
            imageConfig: {
                aspectRatio: aspectRatio || "16:9",
                imageSize: '1K',
            },
            safetySettings: [{
                category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                threshold: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            }]
        }

        const img1base64 = loadImage(images[0].path, images[0].mimetype);
        const img2base64 = images[1] ? loadImage(images[1].path, images[1].mimetype) : null;

        const prompt = {
            text: `Combine the person and the product into a realistic photo. Make the person naturally hold or use the product. Match lighting, shadows, scale and perspective.
    Make the person stand in professional studio lighting. Output ecommerce-quality photo realistic imagery.
    ${userPrompt}`
        }

        const response: any = await ai.models.generateContent({
            model,
            contents: img2base64 ? [img1base64, img2base64, prompt] : [img1base64, prompt],
            config: generationConfig,
        });

        if (!response?.candidates?.[0]?.content?.parts) {
            throw new Error("Unexpected response from AI model");
        }

        const parts = response.candidates[0].content.parts;
        let finalBuffer: Buffer | null = null;

        for (const part of parts) {
            if (part.inlineData) {
                const imgBuffer = Buffer.from(part.inlineData.data, 'base64');
                finalBuffer = finalBuffer ? Buffer.concat([finalBuffer, imgBuffer]) : imgBuffer;
            }
        }

        if (!finalBuffer) {
            throw new Error("No image generated by AI model");
        }

        const base64Image = `data:image/png;base64,${finalBuffer.toString('base64')}`;

        const uploadResult = await cloudinary.uploader.upload(base64Image, {
            resource_type: "image",
        });

        await prisma.project.update({
            where: { id: project.id },
            data: { generatedImage: uploadResult.secure_url, isGenerating: false },
        });

        res.json({ projectId: project.id, imageUrl: uploadResult.secure_url });

    } catch (error: any) {
        Sentry.captureException(error);
        return res.status(500).json({ message: error.message || error.code });
    }
};

export const createVideo = async (req: Request, res: Response) => {
    let isCreditDeducted = false;
    try {
        const { userId } = req.auth();
        const projectId = (req.body.projectId as string) || "";
        if (!userId) {
            return res.status(401).json({ message: "Unauthorized" });
        }
        const project = await prisma.project.findUnique({
            where: { id: projectId, userId },
        });
        if (!project || project.isGenerating) {
            return res.status(404).json({ message: "Project not found or already generating" });
        }
        if (project.generatedVideo) {
            return res.status(400).json({ message: "Video already generated for this project" });
        }

        const user = await prisma.user.findUnique({ where: { id: userId } });
        if (!user || user.credits < 10) {
            return res.status(402).json({ message: "Not enough credits" });
        }
        await prisma.user.update({
            where: { id: userId },
            data: { credits: { decrement: 10 } },
        });
        isCreditDeducted = true;

        await prisma.project.update({
            where: { id: projectId },
            data: { isGenerating: true },
        });

        const prompt = `Create a short engaging video showcasing the product ${project.productName} using the image provided. Highlight the key features and benefits of the product in a visually appealing way. The video should be around ${project.targetLength} seconds long and suitable for sharing on social media platforms.`;

        const model = "veo-3.1-generate-preview";
        if (!project.generatedImage) {
            throw new Error("No generated image found for this project");
        }
        const image = await axios.get(project.generatedImage, { responseType: 'arraybuffer' });
        const imageBytes: any = Buffer.from(image.data);
        let operation: any = await ai.models.generateVideos({
            model,
            prompt,
            image: {
                imageBytes: imageBytes.toString('base64'),
                mimeType: "image/png"
            },
            config: {
                aspectRatio: project.aspectRatio || "16:9",
                numberOfVideos: 1,
                resolution: '720p',
            }
        });

        while (!operation.done) {
            console.log("Video generation in progress...");
            await new Promise(resolve => setTimeout(resolve, 5000));
            operation = await ai.operations.getVideosOperation({
                operation: operation.name
            });
        }

        const filename = `${project.id}_${Date.now()}.mp4`;
        const filePath = path.join('videos', filename);
        fs.mkdirSync('videos', { recursive: true });

        if (!operation.response?.generatedVideos) {
            throw new Error(operation.response.raiMediaFilteredReasons?.[0] || "Video generation failed");
        }

        const videoBuffer = Buffer.from(operation.response.generatedVideos[0].videoBytes, 'base64');
        fs.writeFileSync(filePath, videoBuffer);

        const uploadResult = await cloudinary.uploader.upload(filePath, {
            resource_type: "video",
        });

        await prisma.project.update({
            where: { id: project.id },
            data: { generatedVideo: uploadResult.secure_url, isGenerating: false },
        });

        fs.unlinkSync(filePath);
        res.json({ message: "Video generated successfully", videoUrl: uploadResult.secure_url });

    } catch (error: any) {
        await prisma.project.update({
            where: { id: req.body.projectId },
            data: { isGenerating: false, error: error.message },
        });
        if (isCreditDeducted) {
            await prisma.user.update({
                where: { id: req.auth().userId },
                data: { credits: { increment: 10 } },
            });
        }

        Sentry.captureException(error);
        res.status(500).json({ message: error.message });
    }
};

export const getAllPublishedProjects = async (req: Request, res: Response) => {
    try {
        const projects = await prisma.project.findMany({
            where: { isPublished: true },
            orderBy: { createdAt: "desc" },
        });
        res.json({ projects });
    } catch (error: any) {
        Sentry.captureException(error);
        res.status(500).json({ message: error.message });
    }
};

export const deleteProject = async (req: Request, res: Response) => {
    try {
        const { userId } = req.auth();
        const projectId = Array.isArray(req.params.projectId)
            ? req.params.projectId[0]
            : req.params.projectId;
        if (!userId) {
            return res.status(401).json({ message: "Unauthorized" });
        }
        const project = await prisma.project.findUnique({
            where: { id: projectId, userId },
        });
        if (!project) {
            return res.status(404).json({ message: "Project not found" });
        }

        await prisma.project.delete({ where: { id: projectId } });
        res.json({ message: "Project deleted" });
    } catch (error: any) {
        Sentry.captureException(error);
        res.status(500).json({ message: error.message });
    }
};
